server:
  port: 8081
  forward-headers-strategy: native
spring:
  application:
    name: api-gateway-svc
  codec:
    max-in-memory-size: 15MB
  cloud:
    gateway:
      x-forwarded:
        enabled: true
        for-enabled: true
      forwarded:
        enabled: true
      routes:
        - id: user-management-svc
          uri: http://localhost:5000
          predicates:
            - Path=/user/**, /v1/swagger-ui/user/**
        - id: product-svc
          uri: http://localhost:5001
          predicates:
            - Path=/product/**, /search/**, /v1/swagger-ui/product/**
        - id: payment-svc
          uri: http://localhost:5002
          predicates:
            - Path=/payment/**, /v1/swagger-ui/payment/**
        - id: order-management-svc
          uri: http://localhost:5003
          predicates:
            - Path=/order/**, /v1/swagger-ui/order/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG